#!/usr/bin/env ruby
# frozen_string_literal: true
#
# Concepts-index preprocessor.
#
#   ruby tools/build_indexes.rb [src_dir]   (default: ./src)
#
# Scans the .adoc sources for concept markers of the form
#
#     @@CX(Primary Term | optional sub-aspect)@@
#
# placed inline at the sentence that expresses the idea. For each marker it:
#   1. assigns a stable anchor id (concept-NNNN),
#   2. rewrites the marker in place to that inline anchor `[[concept-NNNN]]`
#      (so the prose renders unchanged and Asciidoctor can resolve its page),
#   3. records (primary, secondary, anchor) for the index.
#
# It then writes `src/_generated/concepts-index.adoc`, a description-list grouped
# by primary term (mushaf-independent alpha sort), each sub-aspect linking via
# `xref:concept-NNNN[]` so the PDF prints real page numbers. The master document
# includes that file at the "Index of Concepts and Key Ideas" placeholder.
#
# Idempotent: markers already rewritten to anchors are left alone; re-running only
# processes any new @@CX(...)@@ markers and regenerates the index file.

require 'fileutils'

SRC = ARGV[0] || File.join(__dir__, '..', 'src')
GEN_DIR = File.join(SRC, '_generated')
OUT = File.join(GEN_DIR, 'concepts-index.adoc')

MARKER = /@@CX\((.+?)\)@@/

# Collect existing anchors so ids stay stable across runs and never collide.
existing = []
Dir.glob(File.join(SRC, '**', '*.adoc')).each do |f|
  next if f.start_with?(GEN_DIR)
  File.read(f).scan(/\[\[(concept-\d+)\]\]/) { |m| existing << m[0][/\d+/].to_i }
end
next_id = (existing.max || 0) + 1

entries = []   # {primary:, secondary:, anchor:}

# First, harvest already-anchored concepts? We can't recover their term text from
# the anchor alone, so the index is rebuilt only from live @@CX markers PLUS a
# persisted registry. Keep a registry so anchors created on prior runs still index.
REGISTRY = File.join(GEN_DIR, 'concepts-registry.tsv')
FileUtils.mkdir_p(GEN_DIR)
registry = {}   # anchor -> [primary, secondary]
if File.exist?(REGISTRY)
  File.foreach(REGISTRY) do |line|
    a, p, s = line.chomp.split("\t", 3)
    registry[a] = [p, s.to_s]
  end
end

files = Dir.glob(File.join(SRC, '**', '*.adoc')).reject { |f| f.start_with?(GEN_DIR) }.sort
files.each do |path|
  text = File.read(path)
  next unless text =~ MARKER
  changed = text.gsub(MARKER) do
    raw = Regexp.last_match(1)
    primary, secondary = raw.split('|', 2).map { |x| x.to_s.strip }
    anchor = "concept-#{next_id}"
    next_id += 1
    registry[anchor] = [primary, secondary.to_s]
    "[[#{anchor}]]"
  end
  File.write(path, changed)
end

# Persist registry.
File.open(REGISTRY, 'w') do |f|
  registry.sort_by { |a, _| a[/\d+/].to_i }.each { |a, (p, s)| f.puts([a, p, s].join("\t")) }
end

# Build the grouped index from the registry.
grouped = Hash.new { |h, k| h[k] = [] }
registry.each { |anchor, (primary, secondary)| grouped[primary] << [secondary, anchor] }

lines = []
lines << '// GENERATED by tools/build_indexes.rb — do not edit by hand.'
grouped.keys.sort_by { |k| k.downcase }.each do |primary|
  subs = grouped[primary]
  bare = subs.select { |sec, _| sec.nil? || sec.empty? }
  withsub = subs.reject { |sec, _| sec.nil? || sec.empty? }
  if withsub.empty?
    refs = bare.map { |_, a| "xref:#{a}[▸]" }.join(', ')
    lines << "*#{primary}*:: #{refs}"
  else
    lines << "*#{primary}*::"
    # any page refs attached directly to the primary
    unless bare.empty?
      lines << "  (general)::: #{bare.map { |_, a| "xref:#{a}[▸]" }.join(', ')}"
    end
    withsub.sort_by { |sec, _| sec.downcase }
           .group_by { |sec, _| sec }
           .each do |sec, group|
      refs = group.map { |_, a| "xref:#{a}[▸]" }.join(', ')
      lines << "  #{sec}::: #{refs}"
    end
  end
end

File.write(OUT, lines.join("\n") + "\n")
puts "Concepts index: #{registry.size} entries across #{grouped.size} primary terms -> #{OUT.sub(%r{\A.*/src/}, 'src/')}"
