#!/usr/bin/env ruby
# frozen_string_literal: true
#
# Concepts-index preprocessor — NON-DESTRUCTIVE.
#
#   ruby tools/build_indexes.rb               (default src=./src, out=./build/render)
#   ruby tools/build_indexes.rb SRC OUTDIR
#
# Reads the AsciiDoc sources (which contain concept markers of the form
#   @@CX(Primary Term | optional sub-aspect)@@
# placed inline at the sentence that expresses the idea) and writes a PROCESSED
# COPY of the whole src tree into OUTDIR, in which each marker is replaced by an
# inline anchor [[concept-NNNN]]. It also writes OUTDIR/_generated/concepts-index.adoc
# (a description list grouped by primary, each sub-aspect linking via xref to its
# anchor so the PDF prints real page numbers).
#
# CRUCIAL: the committed sources under SRC are NEVER modified. The concept TERM
# TEXT lives permanently in the @@CX(...)@@ markers in the source, so nothing here
# is lossy — delete OUTDIR anytime and rebuild.
#
# The master render doc is OUTDIR/book.adoc; build.sh renders from there.

require 'fileutils'

SRC = ARGV[0] || File.join(__dir__, '..', 'src')
OUTDIR = ARGV[1] || File.join(__dir__, '..', 'build', 'render')
MARKER = /@@CX\((.+?)\)@@/

FileUtils.rm_rf(OUTDIR)
FileUtils.mkdir_p(OUTDIR)

# Copy the whole source tree to OUTDIR (so includes resolve identically).
Dir.glob(File.join(SRC, '**', '*')).each do |path|
  rel = path.sub(/\A#{Regexp.escape(SRC)}\/?/, '')
  dest = File.join(OUTDIR, rel)
  if File.directory?(path)
    FileUtils.mkdir_p(dest)
  else
    FileUtils.mkdir_p(File.dirname(dest))
    FileUtils.cp(path, dest)
  end
end

# Walk the COPIES, replace markers with anchors, collect (primary, sub, anchor).
# Skip AsciiDoc line comments (// ...) so a marker shown literally in a doc
# comment (e.g. the explanatory note in book.adoc) is not treated as real.
entries = []   # [primary, sub, anchor]
counter = 0
Dir.glob(File.join(OUTDIR, '**', '*.adoc')).sort.each do |path|
  next if path.include?('/_generated/')
  text = File.read(path)
  next unless text =~ MARKER
  lines = text.lines.map do |line|
    next line if line.lstrip.start_with?('//')   # leave comment lines untouched
    line.gsub(MARKER) do
      raw = Regexp.last_match(1)
      primary, sub = raw.split('|', 2).map { |x| x.to_s.strip }
      counter += 1
      anchor = "concept-#{counter}"
      entries << [primary, sub.to_s, anchor]
      "[[#{anchor}]]"
    end
  end
  text = lines.join
  File.write(path, text)
end

# Build the grouped index.
grouped = Hash.new { |h, k| h[k] = [] }
entries.each { |primary, sub, anchor| grouped[primary] << [sub, anchor] }

lines = ['// GENERATED by tools/build_indexes.rb — do not edit by hand.']
grouped.keys.sort_by { |k| k.gsub(/[^a-zA-Z0-9]/, '').downcase }.each do |primary|
  subs = grouped[primary]
  bare = subs.select { |s, _| s.nil? || s.empty? }
  withsub = subs.reject { |s, _| s.nil? || s.empty? }
  if withsub.empty?
    lines << "*#{primary}*:: #{bare.map { |_, a| "xref:#{a}[▸]" }.join(', ')}"
  else
    lines << "*#{primary}*::"
    lines << "  (general)::: #{bare.map { |_, a| "xref:#{a}[▸]" }.join(', ')}" unless bare.empty?
    withsub.group_by { |s, _| s }.sort_by { |s, _| s.downcase }.each do |sub, grp|
      lines << "  #{sub}::: #{grp.map { |_, a| "xref:#{a}[▸]" }.join(', ')}"
    end
  end
end

gen_dir = File.join(OUTDIR, '_generated')
FileUtils.mkdir_p(gen_dir)
File.write(File.join(gen_dir, 'concepts-index.adoc'), lines.join("\n") + "\n")

puts "Concepts index: #{entries.size} entries across #{grouped.size} primary terms"
puts "Render tree: #{OUTDIR.sub(%r{\A.*/book_en/}, '')}"
